services:
  postgres:
    image: postgres:16
    container_name: smde-pg-container
    restart: "no"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smde_db
    ports:
      - "5433:5432"
    volumes:
      - smde:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d root"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  smde:
